version: "3.4"
services:
  rabbit_test:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: builder
    container_name: rabbit-test
    command:  sh -c 'wait-for postgres-local:5432 --timeout=60 && wait-for redis-local:6379 --timeout=60 && cd app && fresh'
    depends_on:
      - postgres-local
    volumes:
      - ../..:/go/src/gitlab.com/rabbit-test
    ports:
      - "8080:8080"
    environment:
      APP_NAME: rabbit-test
      POSTGRES_DB: rabbit_db
      POSTGRES_HOST: postgres-local
      POSTGRES_PASSWORD: mypass
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      REDIS_HOST: redis-local
      REDIS_PORT: 6379
      REDIS_DB: 1
      REDIS_ITEM_TTL: 10
      REDIS_PASSWORD: mypass
      BASE_URL: "http://localhost:8080/"
      BLACKLIST_URL: "google.*"

  postgres-local:
    image: "postgres:10-alpine"
    container_name: postgres-local
    volumes:
      - ./postgres/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./postgres/db:/var/lib/postgresql/data
    restart: 'always'
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rabbit_db
      POSTGRES_HOST: postgres-local
      POSTGRES_PASSWORD: mypass
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres

  redis-local:
    image: "redis:6-alpine"
    container_name: redis-local
    command: redis-server --requirepass mypass
    restart: 'always'
    expose:
      - 6379
    ports:
      - "6379:6379"
